// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPaths(arg1) {
  return window['go']['main']['App']['AddPaths'](arg1);
}

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function CreateProject(arg1, arg2) {
  return window['go']['main']['App']['CreateProject'](arg1, arg2);
}

export function DataDirSize() {
  return window['go']['main']['App']['DataDirSize']();
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DownloadFFmpeg() {
  return window['go']['main']['App']['DownloadFFmpeg']();
}

export function Export(arg1) {
  return window['go']['main']['App']['Export'](arg1);
}

export function ExportPlan(arg1) {
  return window['go']['main']['App']['ExportPlan'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function Models() {
  return window['go']['main']['App']['Models']();
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function PickDataDir() {
  return window['go']['main']['App']['PickDataDir']();
}

export function PickExportPath(arg1, arg2) {
  return window['go']['main']['App']['PickExportPath'](arg1, arg2);
}

export function PickVideoFiles() {
  return window['go']['main']['App']['PickVideoFiles']();
}

export function PickVideoFolder() {
  return window['go']['main']['App']['PickVideoFolder']();
}

export function ProxyURL(arg1) {
  return window['go']['main']['App']['ProxyURL'](arg1);
}

export function RecheckFFmpeg() {
  return window['go']['main']['App']['RecheckFFmpeg']();
}

export function Refresh() {
  return window['go']['main']['App']['Refresh']();
}

export function RemoveVideo(arg1) {
  return window['go']['main']['App']['RemoveVideo'](arg1);
}

export function ResetScores() {
  return window['go']['main']['App']['ResetScores']();
}

export function Run(arg1) {
  return window['go']['main']['App']['Run'](arg1);
}

export function SetAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SetAPIKey'](arg1, arg2);
}

export function SetDataDir(arg1, arg2) {
  return window['go']['main']['App']['SetDataDir'](arg1, arg2);
}

export function SetGame(arg1) {
  return window['go']['main']['App']['SetGame'](arg1);
}

export function SetLang(arg1) {
  return window['go']['main']['App']['SetLang'](arg1);
}

export function SetManualScore(arg1, arg2) {
  return window['go']['main']['App']['SetManualScore'](arg1, arg2);
}

export function SetModel(arg1) {
  return window['go']['main']['App']['SetModel'](arg1);
}

export function SetSelected(arg1, arg2) {
  return window['go']['main']['App']['SetSelected'](arg1, arg2);
}

export function SetVideoOrder(arg1) {
  return window['go']['main']['App']['SetVideoOrder'](arg1);
}

export function ShowInFolder(arg1) {
  return window['go']['main']['App']['ShowInFolder'](arg1);
}

export function SortVideosByDate() {
  return window['go']['main']['App']['SortVideosByDate']();
}
