// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddPaths(arg1:Array<string>):Promise<main.ProjectView>;

export function Cancel():Promise<void>;

export function CreateProject(arg1:string,arg2:string):Promise<main.ProjectView>;

export function DataDirSize():Promise<number>;

export function DeleteProject(arg1:string):Promise<void>;

export function DownloadFFmpeg():Promise<void>;

export function Export(arg1:main.ExportOptions):Promise<void>;

export function ExportPlan(arg1:number):Promise<main.PlanView>;

export function GetSettings():Promise<main.SettingsView>;

export function ListProjects():Promise<Array<main.ProjectSummary>>;

export function Models():Promise<Array<main.ModelInfo>>;

export function OpenDataDir():Promise<void>;

export function OpenProject(arg1:string):Promise<main.ProjectView>;

export function PickDataDir():Promise<string>;

export function PickExportPath(arg1:string,arg2:string):Promise<string>;

export function PickVideoFiles():Promise<Array<string>>;

export function PickVideoFolder():Promise<string>;

export function ProxyURL(arg1:number):Promise<string>;

export function RecheckFFmpeg():Promise<main.SettingsView>;

export function Refresh():Promise<main.ProjectView>;

export function RemoveVideo(arg1:number):Promise<main.ProjectView>;

export function ResetScores():Promise<void>;

export function Run(arg1:Array<string>):Promise<void>;

export function SetAPIKey(arg1:string,arg2:boolean):Promise<void>;

export function SetDataDir(arg1:string,arg2:boolean):Promise<void>;

export function SetGame(arg1:string):Promise<main.ProjectView>;

export function SetLang(arg1:string):Promise<void>;

export function SetManualScore(arg1:number,arg2:number):Promise<void>;

export function SetModel(arg1:string):Promise<void>;

export function SetSelected(arg1:number,arg2:number):Promise<void>;

export function SetVideoOrder(arg1:Array<number>):Promise<main.ProjectView>;

export function ShowInFolder(arg1:string):Promise<void>;

export function SortVideosByDate():Promise<main.ProjectView>;
